version: '3.8'
services:
  db:
    image: postgres:15-alpine # 使用轻量级版 PG
    container_name: shopping-cart-db
    restart: always
    ports:
      - '5432:5432' # 把容器里的 5432 端口映射到你电脑的 5432
    environment:
      POSTGRES_USER: myuser # 数据库账号
      POSTGRES_PASSWORD: mypassword # 数据库密码
      POSTGRES_DB: shopping_cart # 数据库名字
    volumes:
      - postgres_data:/var/lib/postgresql/data # 数据持久化，防止重启 Docker 数据丢失

volumes:
  postgres_data:
